export default Object.freeze({
    CLEAR_ALL: 'CLEAR_ALL_TRANSACTIONS',
    CLEAR: 'CLEAR_TRANSACTION',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    CHECK_TRANSACTION: 'CHECK_FOR_TRANSACTION',
    APPROVE_TRANSACTION: 'APPROVE_TRANSACTION',
    DENY_TRANSACTION: 'DENY_TRANSACTION'
});
