require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'verify', {
  'Debug' => :debug,
  'DebugAlfa' => :debug,
  'DebugFBG' => :debug,
  'Release' => :release,
  'ReleaseAlfa' => :release,
  'ReleaseFBG' => :release
}

ENVFILES = {
  'Debug' => '$(PODS_ROOT)/../../.env.highrise',
  'DebugAlfa' => '$(PODS_ROOT)/../../.env.alfalah',
  'DebugFBG' => '$(PODS_ROOT)/../../.env.fidelity',
  'Release' => '$(PODS_ROOT)/../../.env.highrise',
  'ReleaseAlfa' => '$(PODS_ROOT)/../../.env.alfalah',
  'ReleaseFBG' => '$(PODS_ROOT)/../../.env.fidelity'
}

target 'verify' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  
  


  target 'verifyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '~> 1.4' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
  end
end
target 'verify-tvOS' do
  # Pods for verify-tvOS

  target 'verify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
