const ACCOUNT_METHODS = Object.freeze({
    FINGERPRINT: 'FINGERPRINT_METHOD',
    USER_PRESENCE: 'USER_PRESENCE_METHOD',
    TOTP: 'TOTP_METHOD',
    FACE_ID: 'FACE_ID_METHOD'
});

const ERROR_MESSAGES = Object.freeze({
    INVALID_QR: 'INVALID_QR_CODE',
    DETAILS_FETCH: 'ERROR_FETCHING_DETAILS',
    TOKEN_FETCH: 'ERROR_FETCHING_TOKEN',
    USER_PRESENCE_REGISTER: 'ERROR_REGISTERING_USER_PRESENCE',
    TOTP_REGISTER: 'ERROR_REGISTERING_TOTP',
    FINGERPRINT_REGISTER: 'ERROR_REGISTERING_FINGERPRINT'
});

const APP_INFO = Object.freeze({
    VERSION: '1.0.0'
});

export default { ACCOUNT_METHODS, ERROR_MESSAGES, APP_INFO };
export { ACCOUNT_METHODS, ERROR_MESSAGES, APP_INFO };
