const constants = Object.freeze({
    INIT: 'INITIALIZE_MAIN_SCREEN',
    SELECT_ACCOUNT: 'SELECT_AN_ACCOUNT',
    UNSELECT_ACCOUNT: 'UNSELECT_ACCOUNT',
    SET_TRANSACTION: 'ADD_TRANSACTION_TO_ACCOUNT',
    CHECK_TRANSACTION: 'CHECK_FOR_TRANSACTION',
    SET_SELECTED_ACCOUNT_TRANSACTION: 'CHECK_FOR_TRANSACTION_OF_SELECTED'
});

export default constants;
