const constants = Object.freeze({
    INIT: 'INITIALIZE_MAIN_SCREEN',
    SELECT_ACCOUNT: 'SELECT_AN_ACCOUNT',
    UNSELECT_ACCOUNT: 'UNSELECT_ACCOUNT',
    SET_TRANSACTION: 'ADD_TRANSACTION_TO_ACCOUNT'
});

export default constants;
